### ISSUE TITLE
Settings Page: Array to string conversion in core SettingsMetadata class

### ISSUE THREAD

**Issue by jofranz** [Project60/org.project60.membership#70]
## Having
- CiviCRM 5.65.2
- PHP 8.1
- Error logs enabled in frontend: `admin/config/development/logging`

## Steps
Go to the settings page: ```.../civicrm/admin/setting/membership```

## See
508x warnings:
```Warning: Array to string conversion in Civi\Core\SettingsMetadata::_filterSettingsSpecification() (line 133 of /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/Civi/Core/SettingsMetadata.php)

#0 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/includes/bootstrap.inc(164): _drupal_error_handler_real()
#1 [internal function]: _drupal_error_handler()
#2 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/Civi/Core/SettingsMetadata.php(133): array_intersect_assoc()
#3 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/Civi/Core/SettingsMetadata.php(71): Civi\Core\SettingsMetadata::_filterSettingsSpecification()
#4 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Admin/Form/SettingTrait.php(69): Civi\Core\SettingsMetadata::getMetadata()
#5 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Admin/Form/SettingTrait.php(152): CRM_Admin_Form_Setting->getSettingsMetaData()
#6 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Admin/Form/SettingTrait.php(274): CRM_Admin_Form_Setting->getSettingsOrderedByWeight()
#7 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Admin/Form/Setting.php(66): CRM_Admin_Form_Setting->addFieldsDefinedInSettingsMetadata()
#8 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/sites/default/files/civicrm/ext/org.project60.membership/CRM/Admin/Form/Setting/MembershipExtension.php(213): CRM_Admin_Form_Setting->buildQuickForm()
#9 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Core/Form.php(740): CRM_Admin_Form_Setting_MembershipExtension->buildQuickForm()
#10 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Core/QuickForm/Action/Display.php(76): CRM_Core_Form->buildForm()
#11 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform()
#12 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle()
#13 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Core/Controller.php(355): HTML_QuickForm_Page->handle()
#14 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Utils/Wrapper.php(98): CRM_Core_Controller->run()
#15 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(292): CRM_Utils_Wrapper->run()
#16 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem()
#17 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke()
#18 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/modules/contrib/civicrm/src/Civicrm.php(88): CRM_Core_Invoke::invoke()
#19 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/modules/contrib/civicrm/src/Controller/CivicrmController.php(83): Drupal\civicrm\Civicrm->invoke()
#20 [internal function]: Drupal\civicrm\Controller\CivicrmController->main()
#21 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#22 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(583): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#23 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#24 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#25 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/symfony/http-kernel/HttpKernel.php(166): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#26 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#27 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#28 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#29 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#30 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#31 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#32 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#33 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#34 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
#35 /var/www/vhosts/CUSTOMER/httpdocs/dev/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#36 {main}
```

____
_Internal ref. 19731_

**Comment by lukasschreiber** [comment]
I have the same issue on Wordpress. Is there any temporary solution other than downgrading from civicrm 5.6*? @bjendres

**Comment by bjendres** [comment]
Does anyone already a fix for this?

**Comment by peth-systopia** [comment]
We have no plans to do further work on this at the moment. If you would like us to work on a fix, please [get in touch](mailto:info@systopia.de) for a quote @lukasschreiber. Thanks!
